### ISSUE TITLE
Expose "Socket" class

### ISSUE THREAD

**Issue by henopied** [uWebSockets/uWebSockets#184] opened 2016-07-11 15:26 UTC
I am trying to use this module with a project that is currently using ws [MultiOgar](https://github.com/Barbosik/MultiOgar). But when using ws he can just add stuff to the ws client prototype. He can't do that with uws though as the client is not exposed in any way.

**Comment by alexhultman** [comment] 2016-07-11 15:29
There is no client support. This is only a server currently. We might add client support in the future, it is on a separate branch but will need to also be wrapped up in JS.

**Comment by alexhultman** [comment] 2016-07-11 15:30
#171

**Comment by henopied** [comment] 2016-07-11 15:55
I mean like the socket connection class.

**Comment by alexhultman** [comment] 2016-07-11 16:05
So this is #142?

require('uws') should evaluate to Socket?

**Comment by henopied** [comment] 2016-07-11 16:12
Very similar to that, but if you do that it may confuse some users into thinking there is already full client support so may want to expose it as `require('uws').Socket`

**Comment by alexhultman** [comment] 2016-07-11 16:22
I get it, thanks for reporting this. I have completely misunderstood the prior bug reports. This should be easy to fix.

**Comment by henopied** [comment] 2016-07-11 17:59
`exports.Socket = Socket`

**Comment by alexhultman** [comment] 2016-07-12 17:35
The problem is, I want to export it just like ws does. I cannot get this to work:

exports = Socket; // this line is added
exports.Server = Server;
exports.uws = uws;

require('uws') should evaluate to Socket while require('uws').Server should evaluate to Server

**Comment by henopied** [comment] 2016-07-12 17:39
I see, maybe use module.exports instead of exports or would that cause other issues?

**Comment by alexhultman** [comment] 2016-07-12 17:40
module.exports worked. I thought exports were the same as module.exports...

**Comment by henopied** [comment] 2016-07-12 17:41
No side effects?

**Comment by SEAPUNK** [comment] 2016-07-12 17:44
`exports` is the same as `module.exports`, with the difference of it being a variable, instead of a property, so you're just reassigning the variable, instead of modifying a property on the `module` object.

```js
const obj = {
  a: '5'
}

obj.a = '4'
let a = obj.a
a = '3'
obj.a // '4'
```

**Comment by alexhultman** [comment] 2016-07-12 18:29
Basically I need to do `module.exports = Socket;` and move all my exports into getters of the Socket class?

```javascript
exports.PERMESSAGE_DEFLATE = 1;
exports.SERVER_NO_CONTEXT_TAKEOVER = 2;
exports.CLIENT_NO_CONTEXT_TAKEOVER = 4;
exports.OPCODE_TEXT = 1;
exports.OPCODE_BINARY = 2;
exports.OPCODE_PING = 9;
```

These are overwritten by `module.exports = Socket;` so they need to be properties of the Socket class.

**Comment by alexhultman** [comment] 2016-07-12 18:30
```javascript
    static get Server() {
        return Server;
    }
```
I have this as a static getter in the Socket class.

**Comment by SEAPUNK** [comment] 2016-07-12 18:35
Yeah, you'll either have to move the export lines below the `module.exports = ` part (which will be the same as `Socket.OPCODE_PING = 9`

```js
module.exports = Socket
exports // Socket
exports.OPCODE_PING = 9
Socket.OPCODE_PING === 9
```

or move the static getters to the Socket class. It should have the same effect.

**Comment by alexhultman** [comment] 2016-07-12 19:03
99befd1c0d84e63e09172f6212074d8a667c42c9

Still need to test this with primus. Cannot get my primus to work though, says client libraries are not compiled and I cannot find any info on wtf it means.

**Comment by alexhultman** [comment] 2016-07-12 19:10
It works.

**Closed by alexhultman** 2016-07-12 19:10 UTC
Labels: enhancement, js
