### ISSUE TITLE
[node.js binding] How to get remote client ip in correct way?

### ISSUE THREAD

**Issue by Barbosik** [uWebSockets/uWebSockets#224] opened 2016-08-26 13:32 UTC
I added uws to MultiOgar, but there is an issue with remote ip. The way which works with ws module (ws._socket.remoteAddress) doesn't works with uws. 
What is correct way to get remote address address for uws module?

**Comment by alexhultman** [comment] 2016-08-27 20:23
https://github.com/uWebSockets/uWebSockets/blob/master/nodejs/dist/uws.js#L253

It's the same. You can't get this from a closed socket though.

**Comment by silverwind** [comment] 2016-09-04 20:29
Alternatively, `req.upgradeReq.connection.remoteAddress` also works.

**Comment by lpinca** [comment] 2016-09-07 18:56
@silverwind yeah but that [`upgradeReq`](https://github.com/uWebSockets/uWebSockets/blob/59e407907cc1960e40a2a8d6aaa5b499f1b27bdd/nodejs/dist/uws.js#L418-L422) is just a pruned object and uses the [`_socket`](https://github.com/uWebSockets/uWebSockets/blob/59e407907cc1960e40a2a8d6aaa5b499f1b27bdd/nodejs/dist/uws.js#L257-L264) getter anyway.

**Comment by silverwind** [comment] 2016-09-07 21:31
@lpinca care to elborate on what you mean with "pruned object"? When would it fail?

**Comment by lpinca** [comment] 2016-09-08 05:30
Sure, the [`upgradeReq`](https://github.com/uWebSockets/uWebSockets/blob/59e407907cc1960e40a2a8d6aaa5b499f1b27bdd/nodejs/dist/uws.js#L418-L422) is not what you expect to be (the original upgrade request object).
It's an object created ad hoc with only some properties (`url`, and `headers`) copied from the original request object.
The additional `connection` property has nothing to do with the `connection` property of the original upgrade request object, and is just an alias to the [`_socket`](https://github.com/uWebSockets/uWebSockets/blob/59e407907cc1960e40a2a8d6aaa5b499f1b27bdd/nodejs/dist/uws.js#L257-L264) getter.

> When would it fail?

It will fail when the socket is closed, returning an array with 3 `undefined` elements.

**Comment by alexhultman** [comment] 2016-09-10 16:14
#243 Turns out you need to get the address at connection, other places might fail.

**Comment by silverwind** [comment] 2016-09-10 18:57
Hmm wouldn't it be possible to defer closure of the socket until the `close` handler has ran?

**Comment by alexhultman** [comment] 2016-09-10 19:00
I'm doing that currently and I thought it would work, but the issue is getpeername can fail if the kernel considers the connection closed or something. I don't handle any errors from that function so that should probably be added. Point is, getAddress can fail so it's best to call it on connection, or just cache the value in JS code.

**Comment by silverwind** [comment] 2016-09-10 19:24
Yeah, I'll think about doing something like

```js
ws.remoteAddress = ws.upgradeReq.connection.remoteAddress;
ws.remotePort = ws.upgradeReq.connection.remotePort;
```
but I hope we find the root cause on why it fails.

**Comment by alexhultman** [comment] 2016-09-10 19:26
http://man7.org/linux/man-pages/man2/getpeername.2.html

It's just a matter of checking errno after it returns -1 and see what error it is. Probably something like ENOTCONN.

**Comment by alexhultman** [comment] 2016-09-10 19:43
Yep it fails with ENOTCONN and I get tons of Valgrind warnings. I fixed that by returning an address that can be checked for validity. I'm pretty sure I never close a socket before the disconnectionCallback gets called so yeah, seems like the nature of Unix networking. Will check this up though.

**Comment by alexhultman** [comment] 2016-09-10 19:51
The only place in the entire code I call close(fd) is in WebSocket::close(...) and that gets called after the disconnectionCallback. So I guess a connection can be closed by itself when for instance doing a send that fails and returns a broken pipe or something like that. I guess the kernel just removes everything it knows about the socket as soon as it determines the connection broken. I'm no expert at Unix networking but it has to be something like that. Yeah so best bet is probably to get and cache the address on connection, or live dangerously and get it on disconnection but maybe end up with an invalid address you cannot use.

**Closed** 2016-09-15 20:26 UTC

**Comment by marchaos** [comment] 2016-11-25 10:50
It's not obvious from this discussion what the best approach to get the client address is. Can we have this documented somewhere please?

**Comment by marchaos** [comment] 2017-01-10 14:09
If anyone is using uWS with socket.io and wants to get the client address, you can use: 

`socket.conn.transport.socket._socket.remoteAddress`

**Comment by sravanisomepalli6** [comment] 2017-05-23 10:25
ws.upgradeReq.connection.remoteAddress
while using this i am getting error as connection undefined.... Pls help..

webSocketServerObject.on('connection',function(socketObject){
	socketObject.on('message',function(message){
		console.log('The' + message +'Message Received from \n from IP ' + socketObject.upgradeReq.connection.remoteAddress);
    socketObject.send("Received " + message);	
	});
   socketObject.on('close',function(c,d){
	   console.log('Disconnect ' + c + ' -- ' + d);
   });	
});
